version: '3'
services:

  # TODO: consider persisting the database (e.g. Docker mount locally),
  # ... but would need "drop all" tooling first??
  db:
    build: ./db
    restart: always
    networks:
      - backend
    # stdin_open: true # docker run -i
    # tty: true        # docker run -t
    expose:
      - 5432
    # TODO: move to ".dev.yml" (only useful when running dev server on host)
    ports:
      - 5432:5432

  api:
    build:
      context: ./api
      target: dev_target
    restart: always
    volumes:
      - ./api/src:/home/node/app/src
      - ./api/nodemon.json:/home/node/app/nodemon.json
    environment:
      PORT: 8080
      # TODO: password/secrets management
      DB_URL: postgresql://eblackwelder:assessment@db:5432/stratusgrid
    ports:
      - 8080:8080
    expose:
      - 8080
    networks:
      - frontend
      - backend
    depends_on:
      - db
  
  # ui:
  #   build: ./ui
  #   restart: always
  #   ports:
  #     - 8000:8000
  #   depends_on: 
  #     - backend
  #   networks:
  #     - frontend

networks:
  frontend:
  backend:

# volumes:
#   db-data:
